# Generated by Django 4.1.4 on 2023-03-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupadtes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpadtes',
            new_name='OrderUpdate',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timetamp',
            new_name='timestamp',
        ),
    ]
