# Generated by Django 4.1.4 on 2023-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salecart_name', models.CharField(max_length=50)),
            ],
        ),
    ]
