# Generated by Django 4.1.4 on 2023-04-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_salecart'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecart',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
