# Generated by Django 4.1.4 on 2023-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_salecart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecart',
            name='image',
            field=models.ImageField(default='', upload_to='shop/slidesImage'),
        ),
    ]
