# Generated by Django 4.1.4 on 2023-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_salecart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecart',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salecart',
            name='salecount',
            field=models.IntegerField(default=0),
        ),
    ]
